Update script

diff --git a/.github/workflows/check-dangling-commits.yml b/.github/workflows/check-dangling-commits.yml
--- a/.github/workflows/check-dangling-commits.yml
+++ b/.github/workflows/check-dangling-commits.yml
@@ -1,8 +1,6 @@
 name: Checking dangling commits
 
 on:
-  schedule:
-    - cron: '0 0 * * *'
   workflow_dispatch:
     inputs:
       dryRun:
@@ -59,11 +57,22 @@ jobs:
             for REPO in "${REPO_LIST[@]}"; do
               echo "🚨 Scanning $ORG/$REPO ..."
               rm -rf "$REPO"
-              git clone https://github.com/$ORG/$REPO.git
+              if ! git clone https://x-access-token:${GITHUB_TOKEN}@github.com/$ORG/$REPO.git; then
+                echo "❌ Failed to clone $ORG/$REPO. Skipping..."
+                continue
+              fi
               cd "$REPO"
 
               gitleaks detect --source=. --report-path="../gitleaks-reports/${ORG}__${REPO}.json" \
                 --report-format=json --redact || true
+
+              RESULT=$?
+              if [ $RESULT -ne 0 ]; then
+                mv tmp-report.json "../gitleaks-reports/${ORG}__${REPO}.json"
+                echo "🧨 Leaks found in $ORG/$REPO"
+              else
+                echo "✅ No leaks in $ORG/$REPO"
+              fi
 
               cd ..
               rm -rf "$REPO"
